version: "3.3"
services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - /mnt/scalelite-recordings:/mnt/scalelite-recordings
      - /tmp:/home/bigbluebutton/tmp
    security_opt:
      - seccomp:"./chrome.json"